#!/bin/bash

###Get user data
read -p "Enter hostname: " HOSTNAME
read -p "Enter username: " USERNAME
read -p "Enter password: " PASSWORD

read -p "EFI: " EFI_PART
read -p "Swap: " SWAP_PART
read -p "Root: " ROOT_PART

ANSWER=""
while [[ $ANSWER != "n" && $ANSWER != "y" ]] do
	read -p "Continue?[y/n]: " temp
	ANSWER=$temp
done

if [[ $ANSWER == "n" ]] then
    exit
fi

###Setup
setfont ter-c32b
timedatectl set-timezone Europe/Samara
mount --mkdir $ROOT_PART /mnt
mount --mkdir $EFI_PART /mnt/boot/efi

#Pacman
echo '[multilib]' >> /etc/pacman.conf
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
echo 'ParallelDownloads = 15' >> /etc/pacman.conf
reflector --latest 20 --sort rate --save /etc/pacman.d/mirrorlist
pacman -Sy

pacstrap -K /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
#echo '\n' >> /mnt/eft/fstab
#echo '# /dev/sdb1' >> /mnt/eft/fstab
#echo 'UUID=9b066c34-bdf8-405d-88c6-ceb094c75c7e	/mnt/Storage	ext4	defaults,X-mount.mkdir	0 3' >> /mnt/eft/fstab

arch-chroot /mnt bash -c "
    echo '[multilib]' >> /etc/pacman.conf
    echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
    echo 'ParallelDownloads = 15' >> /etc/pacman.conf
    pacman -Sy
    pacman -S man-db man-pages man-pages-ru vim networkmanager git base-devel terminus-font noto-fonts-cjk otf-hermit-nerd kitty grub os-prober efibootmgr mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon vulkan-intel lib32-vulkan-intel steam pipewire lib32-pipewire pipewire-alsa pipewire-pulse pipewire-jack lib32-pipewire-jack xorg-server-xwayland telegram-desktop waybar mono mpd ncmpcpp doublecmd rofi gnome-keyring wl-clipboard wine wev webkit2gtk virt-manager qemu-base qbittorrent papirus-icon-theme obs-studio mpv libva-utils libva-mesa-driver libnotify intel-gpu-tools hyprland engrampa dunst dnsmasq alsa-utils

    ln -sf /usr/share/zoneinfo/Europe/Samara /etc/localtime
    hwclock --systohc

    echo 'ru_RU.UTF-8 UTF-8' >> /etc/locale.gen
    echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
    locale-gen
    echo 'LANG=en_US.UTF-8' >> /etc/locale.conf

    echo 'FONT=ter-c32b' >> /etc/vconsole.conf
    echo '$HOSTNAME' >> /etc/hostname
    echo 'root:$ROOTPASS' | chpasswd
    echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

    useradd -m -G wheel,input,libvirt $USERNAME
    echo '$USERNAME:$PASSWORD' | chpasswd

    systemctl enable libvirtd.socket

    cd /home/$USERNAME
    git clone https://aur.archlinux.org/yay.git
    chown -R $USERNAME yay
    su $USERNAME
    cd
    cd yay
    makepkg -si

    yay -S rider untiyhub portproton dotnet-sdk-8 pwvucontrol mission-center xdg-desktop-portal-hyprland jetbrains-toolbox hyprpicker amdapp-sdk mesa-vpdau

    systemctl --user enable mpd

    cd
    mkdir .config
    git clone https://github.com/MrApache/archinstall.git
    cd archinstall/dotfiles/usercfg
    rm -rf /home/$USERNAME/.config/*
    mv * /home/$USERNAME/.config/
    cd ../syscfg
    mv * /etc/

    #INSTALL SPOOFDPI
    exit

    grub-install --target=x86_64-efi
    echo 'GRUB_DISABLE_OS_PROBER=false' >> /etc/default/grub
    grub-mkconfig -o /boot/grub/grub.cfg
    systemctl enable NetworkManager
"
