#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
#PS1='[\u@\h \W]\$ '

GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"
PS1="[${GREEN}\w${RESET}]\n> "
export BEMENU_SCALE=2
export WLC_REPEAT_RATE=100
export WLC_REPEAT_DELAY=250
